import Head from 'next/head';
import Layout from '../src/components/layout';
import Pixel from '../src/components/pixel';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Contego Spa Designs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <section className="">
          <div className="w-full text-center bg-amber-300 py-7">
            <h1 className="text-xl font-semibold">
              "Ghế Contego hoàn toàn{' '}
              <span className="text-red-700">PERFECT</span>
            </h1>
            <h1 className="text-xl font-semibold">
              Rất <span className="text-red-700">SMART</span> cho người thợ
              nail"
            </h1>
          </div>
          <div className="relative h-[220px]">
            <iframe
              src="https://player.vimeo.com/video/494597824"
              autoPlay
              allowFullScreen
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
                width: '100%',
                height: '100%',
              }}
            ></iframe>
          </div>
        </section>
        <div className="mt-5 text-center py-7 border-b-2">
          <h1 className="font-semibold text-xl capitalize ">
            Những Tiện ích dành cho thợ nail{' '}
          </h1>
          <h1 className="font-semibold text-xl capitalize ">
            khi dùng ghế Contego
          </h1>
        </div>
        <section className="">
          <div className="w-full text-center py-5 px-5">
            <h1 className="text-xl font-semibold text-red-700 my-3">
              DISPOSIBLE JET-LINER
            </h1>
            <h1 className="text-xl font-semibold italic">
              <span className="">Công nghệ Bubble Massage nước</span> thay thế
              Jet nam châm, dùng một lần và vứt bỏ hoàn toàn. Đảm bảo vệ sinh
              tuyệt đối
              {/* Công nghệ bubble masasage nước lên lòng bàn chân khách, được
              sử dụng một lần, tiết kiệm thời gian & công sức chùi rửa

              <br /> */}
              {/* công nghệ air bubble massage nước lên lòng bàn chân, dùng một lần, không phải chùi rửa */}
            </h1>
          </div>
          <div className="relative h-[414px]">
            <iframe
              src="https://player.vimeo.com/video/662098416"
              autoPlay
              allowFullScreen
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
                width: '100%',
                height: '100%',
              }}
            ></iframe>
          </div>
        </section>
        <section className="">
          <div className="w-full text-center px-5 py-5">
            <h1 className="text-xl font-semibold text-red-700 my-3">
              HỆ THỐNG OVERFLOW
            </h1>
            <h1 className="text-xl font-semibold italic">
              Thoải mái châm thêm nước mới mà không lo tràn ra ngoài
            </h1>
          </div>
          <div className="relative h-[414px]">
            <iframe
              src="https://player.vimeo.com/video/743307158"
              autoPlay
              allowFullScreen
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
                width: '100%',
                height: '100%',
              }}
            ></iframe>
          </div>
        </section>
        <section className="">
          <div className="w-full text-center px-5 py-5">
            <h1 className="text-xl font-semibold text-red-700 my-3">
              CÔNG NGHỆ EASY DRAIN
            </h1>
            <h1 className="text-xl font-semibold">
              Giúp thợ xả nước nhanh, sạch, và tiện lợi sau khi xong dịch vụ
              pedicure
            </h1>
          </div>
          <div className="relative h-[414px]">
            <iframe
              src="https://player.vimeo.com/video/743306861"
              autoPlay
              allowFullScreen
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
                width: '100%',
                height: '100%',
              }}
            ></iframe>
          </div>
        </section>
        <section className="">
          <div className="w-full text-center px-1 py-7">
            <h1 className="text-xl font-semibold text-red-700 my-3">
              Và những tính năng hữu ích khác
            </h1>
          </div>
          <div className="relative h-[414px]">
            <iframe
              src="https://player.vimeo.com/video/662098381"
              autoPlay
              allowFullScreen
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
                width: '100%',
                height: '100%',
              }}
            ></iframe>
          </div>
        </section>
        <div className="mt-5 text-center py-20 px-2">
          <h1 className="font-semibold text-xl capitalize mb-10">
            Hãy gọi hoặc nhắn tin để được nhân viên tư vấn chi tiết thêm về
            những <span className="text-red-700">Công Nghệ Ghế Contégo</span>
          </h1>
        </div>
      </main>
      <div>
        <Pixel name="FACEBOOK_PIXEL_1" />
      </div>
    </Layout>
  );
}
